files:
  - source: global_packs/required_resources/Tradução DawnCraft PT_BR/assets/dawncraft-quest/lang
    ignore:
      - pt-BR
    translation: global_packs/%original_path%/%original_file_name%
  - source: /global_packs/required_data/DawnCraft_Datapack/data/quest_giver/quests
    ignore:
      - pt-BR
    translation: global_packs/%original_path%/%original_file_name%
